name: Move Issue to Review on Commit
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  projects: write

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue #8 to Review
        uses: actions/add-to-project@v1
        with:
          project-url: "https://github.com/users/andcssantos/projects/4"  # URL do seu GitHub Project
          github-token: ${{ secrets.GH_PERSONAL_TOKEN }}
          issue-number: 8  # Número do Issue que você quer mover
          status: "Review"  # Nome exato da coluna de destino (Review)
